#!/usr/bin/env python
import markup
import sys

from random import randint, choice

under_construction = "./const.gif"

possibilities = [1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,3,4]

"""literally spam images all over the page"""
def spam_images(page, images):
    for image in images:
        for i in xrange(0,choice(possibilities)):
            page.img(
                src=image,
                style='position:absolute; left:%dpx; top:%dpx;' \
                % (randint(0,600), randint(0,600))
            )


def bannerize_under_construction(page):
    imgs = [under_construction]*randint(5,10)
    page.table(markup.oneliner.tr(markup.oneliner.td(markup.oneliner.img(src=imgs))))

def flashy_background(page):
    x = randint(0, 1 << 24)
    color_a = "#%06x" % x
    color_b = "#%06x" % ((1 << 24) - x)
    page.script("""
        function f() {
            if (document.bgColor == "%s") {
                document.bgColor = "%s"
            } else {
                document.bgColor = "%s"
            }
        }

        setInterval(f, 100)
        document.bgColor = "%s"

    """ % (color_a, color_b, color_a, color_a), type="text/javascript")

def add_ie6(page):
    page.script("""
        function y(){
	(function(){var i=0,r=function(n){return Math.floor(Math.random()*n)},f=document.getElementsByTagName('body')[0].getElementsByTagName('*'),o=function(e){return typeof(e.style)=='object'&&e.tagName!='SCRIPT'},s=function(){while(!o(e=f[r(f.length)])){}return e.style};while(i++<5){s().display=r(2)?'block':'inline';s().position=r(2)?'absolute':'relative';s().margin=r(2)?'0':'1em';s().padding=r(2)?'0':'1em';s().width=r(2)?'':'auto';}})();
}
setInterval("y()", 500);

    """, type="text/javascript")

if __name__ == "__main__":
    if len(sys.argv) == 2:
        image_file = sys.argv[1]
        image_file = open(image_file, "r")
        images = []

        for line in image_file.readlines():
            images.append(line)

        page = markup.page()
        page.init(title="horrorgenned page")
        spam_images(page, images)
        flashy_background(page)
        add_ie6(page)
        bannerize_under_construction(page)
        output_html = open("index.html", "w")
        output_html.write(str(page))
        output_html.flush()
        output_html.close()

    else:
        print "usage is ./horrorgen image_file where image file contains a\
        list of newline separated images" 
